# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'ConferenceApp' do
  pod 'SwiftyJSON', '~> 2.1'
  pod 'ObjectMapper', '~> 0.8'
end

target 'ConferenceAppTests' do
  pod 'SwiftyJSON', '~> 2.1'
  pod 'ObjectMapper', '~> 0.8'
end
